[project]
name = "assignment2"
version = "0.1.0"
description = "AI Engineer Club Assignment 2"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.98.0",
    "requests>=2.32.5",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.0",
]
